--update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69921 and Studentuid=15226

update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69638 and Studentuid=53872
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70157 and Studentuid=71096
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70411 and Studentuid=76848
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70409 and Studentuid=95277
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69164 and Studentuid=96261
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69372 and Studentuid=96717
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69287 and Studentuid=97324
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69417 and Studentuid=99161
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70156 and Studentuid=101396
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=67603 and Studentuid=101470
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70146 and Studentuid=102842
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70211 and Studentuid=108344
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=68825 and Studentuid=112019
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=67647 and Studentuid=112611
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=68756 and Studentuid=114938
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69355 and Studentuid=115121
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70148 and Studentuid=115350
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69195 and Studentuid=116193
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69204 and Studentuid=116543
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69373 and Studentuid=116723
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69189 and Studentuid=119567
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70414 and Studentuid=120257
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69459 and Studentuid=120322
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70150 and Studentuid=122725
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70160 and Studentuid=122770
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69272 and Studentuid=123123
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70412 and Studentuid=123478
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=70200 and Studentuid=123478
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69462 and Studentuid=124460
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69728 and Studentuid=124597
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69637 and Studentuid=124673
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69670 and Studentuid=124796
update studentholds set stoptranscript='yes', stoponlineregistration=1 where StudentHoldsID=69804 and Studentuid=125008

